language: erlang

otp_release:
- 17.1

before_install:
- git clone https://github.com/elixir-lang/elixir
- cd elixir && make && cd ..

before_script:
- export PATH=$PWD/elixir/bin:$PATH
- export MIX_ENV=test

script: "mix do local.hex --force, deps.get --only test, test"

# after_script:
# - mix deps.get --only docs
# - MIX_ENV=docs mix inch.report
